name: 'Import package'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: Configuration file
        type: choice
        options:
          - O365ProPlusVisioProProjectPro.xml
          - O365ProPlusOutlookVisioProProjectPro.xml
          - O365ProPlus.xml
          - O365ProPlusRu.xml
          - O365ProPlusOutlook.xml
          - O365Business.xml
          - O365BusinessOutlook.xml
          - O365ProPlusVisioProProjectPro-VDI.xml
          - O365ProPlus-VDI.xml
          - O365Business-VDI.xml
          - O365ProPlusOutlookVisioProProjectPro-VDI.xml
          - O365ProPlusOutlook-VDI.xml
          - O365BusinessOutlook-VDI.xml
      channel:
        description: Update channel
        type: choice
        options:
          - MonthlyEnterprise
          - Current
          - SemiAnnual
          - SemiAnnualPreview
          - CurrentPreview
          - BetaChannel
      companyname:
        description: Company name
        required: false
        default: stealthpuppy
      psadt:
        description: "Use the PSAppDeployToolkit"
        default: false
        type: boolean
      import:
        description: "Import (if not selected, download package from pipeline artifacts)"
        default: true
        type: boolean

jobs:
  new-package:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Test configuration file path
        id: test-config
        shell: powershell
        run: |
          $file = "${{ github.workspace }}\configs\${{ github.event.inputs.configuration }}"
          if (-not (Test-Path -Path $file -PathType Leaf)) {
            throw "Could not find configuration file: $file"
          }

      - name: Install and cache PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v6.2.1
        with:
          modules-to-cache: "Evergreen::, MSAL.PS::, IntuneWin32App::, PSAppDeployToolkit:4.1.5"
          updatable: true
          shell: powershell

      - name: Update Evergreen apps
        id: update-evergreen
        shell: powershell
        run: |
          Import-Module Evergreen -Force
          Update-Evergreen

      # -----------------------------
      # IMPORT PACKAGE (INTUNE MODE)
      # -----------------------------
      - name: Create and Import package
        id: import-package
        if: ${{ github.event.inputs.import == 'true' }}
        shell: powershell
        run: |
          New-Item -Path "${{ github.workspace }}\package" -ItemType Directory -Force

          $params = @{
            TenantId     = "${{ secrets.TENANT_ID }}"
            ClientId     = "${{ secrets.CLIENT_ID }}"
            ClientSecret = "${{ secrets.CLIENT_SECRET }}"
          }
          Connect-MSIntuneGraph @params

          $params = @{
            Path              = "${{ github.workspace }}"
            ConfigurationFile = "${{ github.workspace }}\configs\${{ github.event.inputs.configuration }}"
            Channel           = "${{ github.event.inputs.channel }}"
            CompanyName       = "${{ github.event.inputs.companyname }}"
            TenantId          = "${{ secrets.TENANT_ID }}"
            UsePsadt          = $([bool]::Parse("${{ github.event.inputs.psadt }}"))
          }
          & "${{ github.workspace }}\New-Microsoft365AppsPackage.ps1" @params

      # ---------------------------------------
      # CREATE PACKAGE ONLY (NO INTUNE)
      # ---------------------------------------
      - name: Create package artifact only
        id: create-artifact
        if: ${{ github.event.inputs.import == 'false' }}
        shell: powershell
        run: |
          New-Item -Path "${{ github.workspace }}\package" -ItemType Directory -Force

          $params = @{
            Path              = "${{ github.workspace }}"
            ConfigurationFile = "${{ github.workspace }}\configs\${{ github.event.inputs.configuration }}"
            Channel           = "${{ github.event.inputs.channel }}"
            CompanyName       = "${{ github.event.inputs.companyname }}"
            UsePsadt          = $([bool]::Parse("${{ github.event.inputs.psadt }}"))
            SkipImport        = $true
          }

          & "${{ github.workspace }}\New-Microsoft365AppsPackage.ps1" @params

      - name: Set release parameters
        id: release
        shell: pwsh
        run: |
          $ConfigurationFile = Get-ChildItem "${{ github.workspace }}\package\output\*.xml" | Select-Object -First 1
          $FileName = [IO.Path]::GetFileNameWithoutExtension($ConfigurationFile)
          [xml]$Xml = Get-Content $ConfigurationFile
          $Channel = $Xml.Configuration.Add.Channel
          $Date = Get-Date -Format yyyyMMdd
          $SetupVersion = (Get-Item "${{ github.workspace }}\m365\setup.exe").VersionInfo.FileVersion
          Import-Module Evergreen
          $PsadtVersion = (Get-EvergreenApp -Name "PSAppDeployToolkit").Version

          echo "release=$FileName.$Channel.$Date.${{ github.run_number }}" >> $Env:GITHUB_OUTPUT
          echo "filename=$FileName" >> $Env:GITHUB_OUTPUT
          echo "channel=$Channel" >> $Env:GITHUB_OUTPUT
          echo "setup=$SetupVersion" >> $Env:GITHUB_OUTPUT
          echo "psadt=$PsadtVersion" >> $Env:GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.release.outputs.release }}
          path: |
            ${{ github.workspace }}/package/output/*
